In [12]:
import importlib
from IPython.display import display

from datetime import date
from account import Index, Account, Merge

In [13]:
idx = Index('2021-04', periods=12, freq='M')

In [14]:
amt = 28_000
sales_lgstc = Account(index=idx, title="Sales_Lgstc", bal_strt = amt)
cf_scdd = sales_lgstc.index[[0, 2, 4, 6, 8, 11]]
cf_rate = [0.1, 0.2, 0.2, 0.2, 0.2, 0.1]
cf_amt = [amt * x for x in cf_rate]
sales_lgstc.subscdd(cf_scdd, cf_amt)

In [15]:
sales_lgstc.subamt(date(2021, 10, 31), 4300)

In [16]:
sales_lgstc.df

,add_scdd,add_scdd_cum,sub_scdd,sub_scdd_cum,bal_strt,amt_add,amt_add_cum,amt_sub,amt_sub_cum,bal_end,add_rsdl_cum,sub_rsdl_cum
2021-04-30,0.0,0.0,2800.0,2800.0,28000.0,0.0,0.0,0.0,0.0,28000.0,0.0,2800.0
2021-05-31,0.0,0.0,0.0,2800.0,28000.0,0.0,0.0,0.0,0.0,28000.0,0.0,2800.0
2021-06-30,0.0,0.0,5600.0,8400.0,28000.0,0.0,0.0,0.0,0.0,28000.0,0.0,8400.0
2021-07-31,0.0,0.0,0.0,8400.0,28000.0,0.0,0.0,0.0,0.0,28000.0,0.0,8400.0
2021-08-31,0.0,0.0,5600.0,14000.0,28000.0,0.0,0.0,0.0,0.0,28000.0,0.0,14000.0
2021-09-30,0.0,0.0,0.0,14000.0,28000.0,0.0,0.0,0.0,0.0,28000.0,0.0,14000.0
2021-10-31,0.0,0.0,5600.0,19600.0,28000.0,0.0,0.0,4300.0,4300.0,23700.0,0.0,15300.0
2021-11-30,0.0,0.0,0.0,19600.0,23700.0,0.0,0.0,0.0,4300.0,23700.0,0.0,15300.0
2021-12-31,0.0,0.0,5600.0,25200.0,23700.0,0.0,0.0,0.0,4300.0,23700.0,0.0,20900.0
2022-01-31,0.0,0.0,0.0,25200.0,23700.0,0.0,0.0,0.0,4300.0,23700.0,0.0,20900.0
2022-02-28,0.0,0.0,0.0,25200.0,23700.0,0.0,0.0,0.0,4300.0,23700.0,0.0,20900.0
2022-03-31,0.0,0.0,2800.0,28000.0,23700.0,0.0,0.0,0.0,4300.0,23700.0,0.0,23700.0